name: CI

on:
  push:
    branches:
      - master
      - main
      - "v*"
    tags:
      - "v*"
  pull_request:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup set profile minimal
      - run: rustup show

      - run: cargo check
        env:
          RUSTFLAGS: "-D warnings"

      - run: cargo check --all-targets --features derive_builder
        env:
          RUSTFLAGS: "-D warnings"

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup set profile minimal
      - run: rustup show
      - run: cargo test --features derive_builder

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup set profile minimal
      - run: rustup show
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup set profile minimal
      - run: rustup show
      - run: rustup component add clippy
      - run: cargo clippy -- --deny warnings --allow unknown-lints
